spring:
  profiles:
    active: dev

---

release:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductManagementSystem
    username: root
    password: nayjacyaaa
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
---

dev:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductManagementSystem
    username: root
    password: nayjacyaaa

  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQLDialect
  logging:
    level:
      org.hibernate.SQL: debug
      org.springframework: debug